-- Snowflake DDL for Lab 1 — run once (or use your migration tool).

CREATE TABLE IF NOT EXISTS WEATHER_RAW_DAILY (
  LOCATION_NAME VARCHAR NOT NULL,
  LATITUDE FLOAT,
  LONGITUDE FLOAT,
  DATE DATE NOT NULL,
  TEMP_MAX FLOAT,
  TEMP_MIN FLOAT,
  TEMP_MEAN FLOAT,
  PRECIP_MM FLOAT,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (LOCATION_NAME, DATE)
);

CREATE TABLE IF NOT EXISTS WEATHER_FORECAST_DAILY (
  LOCATION_NAME VARCHAR NOT NULL,
  FORECAST_DATE DATE NOT NULL,
  PREDICTED_TEMP_MAX FLOAT,
  MODEL_NAME VARCHAR,
  TRAIN_START_DATE DATE,
  TRAIN_END_DATE DATE,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (LOCATION_NAME, FORECAST_DATE)
);

CREATE TABLE IF NOT EXISTS WEATHER_FINAL_DAILY (
  location_name VARCHAR,
  date DATE,
  temp_max FLOAT,
  temp_min FLOAT,
  temp_mean FLOAT,
  is_forecast BOOLEAN,
  model_name VARCHAR
);
