-- Reference SQL aligned with the Airflow Python tasks (MERGE + UNION).
-- ETL DAG stages into a temp table then merges into WEATHER_RAW_DAILY.

CREATE OR REPLACE TEMP TABLE TMP_WEATHER_RAW_DAILY (
  LOCATION_NAME STRING,
  LATITUDE FLOAT,
  LONGITUDE FLOAT,
  DATE DATE,
  TEMP_MAX FLOAT,
  TEMP_MIN FLOAT,
  TEMP_MEAN FLOAT,
  PRECIP_MM FLOAT
);

-- After INSERT INTO TMP_WEATHER_RAW_DAILY ... (from application):

MERGE INTO WEATHER_RAW_DAILY t
USING TMP_WEATHER_RAW_DAILY s
  ON t.LOCATION_NAME = s.LOCATION_NAME
 AND t.DATE = s.DATE
WHEN MATCHED THEN UPDATE SET
  t.LATITUDE = s.LATITUDE,
  t.LONGITUDE = s.LONGITUDE,
  t.TEMP_MAX = s.TEMP_MAX,
  t.TEMP_MIN = s.TEMP_MIN,
  t.TEMP_MEAN = s.TEMP_MEAN,
  t.PRECIP_MM = s.PRECIP_MM,
  t.INGESTED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (LOCATION_NAME, LATITUDE, LONGITUDE, DATE, TEMP_MAX, TEMP_MIN, TEMP_MEAN, PRECIP_MM)
VALUES
  (s.LOCATION_NAME, s.LATITUDE, s.LONGITUDE, s.DATE, s.TEMP_MAX, s.TEMP_MIN, s.TEMP_MEAN, s.PRECIP_MM);

-- Forecast DAG: temp stage then merge into WEATHER_FORECAST_DAILY.

CREATE OR REPLACE TEMP TABLE TMP_WEATHER_FORECAST_DAILY (
  LOCATION_NAME STRING,
  FORECAST_DATE DATE,
  PREDICTED_TEMP_MAX FLOAT,
  MODEL_NAME STRING,
  TRAIN_START_DATE DATE,
  TRAIN_END_DATE DATE
);

MERGE INTO WEATHER_FORECAST_DAILY t
USING TMP_WEATHER_FORECAST_DAILY s
  ON t.LOCATION_NAME = s.LOCATION_NAME
 AND t.FORECAST_DATE = s.FORECAST_DATE
WHEN MATCHED THEN UPDATE SET
  t.PREDICTED_TEMP_MAX = s.PREDICTED_TEMP_MAX,
  t.MODEL_NAME = s.MODEL_NAME,
  t.TRAIN_START_DATE = s.TRAIN_START_DATE,
  t.TRAIN_END_DATE = s.TRAIN_END_DATE,
  t.CREATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (LOCATION_NAME, FORECAST_DATE, PREDICTED_TEMP_MAX, MODEL_NAME, TRAIN_START_DATE, TRAIN_END_DATE)
VALUES
  (s.LOCATION_NAME, s.FORECAST_DATE, s.PREDICTED_TEMP_MAX, s.MODEL_NAME, s.TRAIN_START_DATE, s.TRAIN_END_DATE);

-- Final table: union actuals and forecasts (forecast task truncates then reloads).

TRUNCATE TABLE WEATHER_FINAL_DAILY;

INSERT INTO WEATHER_FINAL_DAILY
  (location_name, date, temp_max, temp_min, temp_mean, is_forecast, model_name)
SELECT
  LOCATION_NAME AS location_name,
  DATE AS date,
  TEMP_MAX AS temp_max,
  TEMP_MIN AS temp_min,
  TEMP_MEAN AS temp_mean,
  FALSE AS is_forecast,
  NULL AS model_name
FROM WEATHER_RAW_DAILY
UNION ALL
SELECT
  LOCATION_NAME AS location_name,
  FORECAST_DATE AS date,
  PREDICTED_TEMP_MAX AS temp_max,
  NULL AS temp_min,
  NULL AS temp_mean,
  TRUE AS is_forecast,
  MODEL_NAME AS model_name
FROM WEATHER_FORECAST_DAILY;
